spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 20

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
custom:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: 12345
    maxPoolSize: 20
    maxLifeTime: 1800000

server:
  port: 1100