spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
    maxPoolSize: 20
    maxLifeTime: 1800000
  config:
    activate:
      on-profile: dev

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 20
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping:
                   registerEvent:com.fawry.kafka.events.RegisterEvent,
                  resetPasswordEvent:com.fawry.kafka.events.ResetPasswordEvent

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka


security:
  jwt:
    secret-key: 9SlLvC1uDlj0vN2e5Wh9a692xd4QZuPaoGDHhhvD404OEJI5g/x6iiNaoM/z7PUfoYHwG5pE35426585AWFFXA==

    expiration-time: 900000000
server:
  port: 4041

frontend:
  url: http://localhost
  port: 4200
