server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
custom:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: 12345


